### ISSUE TITLE
Add links to SGC lesson

### ISSUE THREAD

**Issue by CorySchlesener** [dib-lab/dib_rotation#10]
It might be helpful to add the following links
- Tutorial on nano (https://datacarpentry.org/wrangling-genomics/)
- Note to install Bcalm 2 as well via conda (https://github.com/GATB/bcalm#installation)

**Also change RAM on srun. 40 or 60GB not enough. I used 70GB

**Comment by taylorreiter** [comment]
Thanks @CorySchlesener! 

BCALM installation is included when the environment.yml is installed, see: https://github.com/spacegraphcats/spacegraphcats/blob/master/environment.yml

I'll add the bit on nano, and update the ram!

**Comment by taylorreiter** [comment]
Fixed! Thank you
https://github.com/dib-lab/dib_rotation/commit/c64386dea04b2ca966c699ee07be6496d01d2869
