### ISSUE TITLE
Update kofamscan version

### ISSUE THREAD

**Issue by CorySchlesener** [dib-lab/dib_rotation#12]
#Update address for new version of kofamscan
wget ftp://ftp.genome.jp/pub/tools/kofamscan/kofamscan-1.1.0.tar.gz

#Also unzip
tar xf kofamscan-1.1.0.tar.gz

#Add make 'config.yml' in 'kofamscan-1.1.0' directory
nano config.yml

#Run in 'kofamscan' directory as './kofamscan-1.1.0/exec_annotation'

**Comment by taylorreiter** [comment]
closed by #16
