### ISSUE TITLE
install screed

### ISSUE THREAD

**Issue by hehouts** [dib-lab/dib_rotation#13]
screed is apparently not a dependency in sourmash anymore and needs to be installed into the rotation environment before running `python remove-stop-plass.py query_nbhd_plass.fa`

**Comment by ctb** [comment]
hi @hehouts this is strange! could you drop the commands you're using and the error you get into this issue, pls?

**Comment by hehouts** [comment]
I was following the instructions word for word (minus side stepping issue with linked file), and got to this command:

`python remove-stop-plass.py query_nbhd_plass.fa`
(script from https://raw.githubusercontent.com/spacegraphcats/2018-paper-spacegraphcats/master/pipeline-base/scripts/remove-stop-plass.py)

Then got the error message: `ModuleNotFoundError: No module named 'screed'` even though I was in the conda environment set up in this tutorialt that has sourmash up and running.

**Comment by ctb** [comment]
ok, thanks! (it's always nice if you link directly to the section of the
instructions, too, because that way I don't need to know anything about
the project to find the right thing :)

can go activate that environment and give me the results of: 

% type python

and 

python -c "import screed"

pls?

**Comment by hehouts** [comment]
re link to section: will have to figure out how to do that :)

`type python` ->`python is /home/hehouts/miniconda3/envs/dib_rotation/bin/python`

`python -c "import screed"` -> literally nothing. just sat there for ~1 minute then returned prompt 

full disclosure, I entered `python -c import screed`, quote-less, on accident first so I hope that didnt mess it up?

**Comment by ctb** [comment]
On Mon, May 11, 2020 at 02:56:16PM -0700, hehouts wrote:
> re link to section: will have to figure out how to do that :)

just the markdown doc is good enough, but if you find a headline,
you can hover over it and click to the left -- you'll see a link like this:

https://github.com/dib-lab/dib_rotation/blob/master/09_assembling_a_nbhd.md#running-plass-and-formatting-the-output


> `type python` ->`python is /home/hehouts/miniconda3/envs/dib_rotation/bin/python`

ok!
> 
> `python -c "import screed"` -> literally nothing. just sat there for ~1 minute then returned prompt 

huh. that implies that it worked.

can you try running

% python remove-stop-plass.py query_nbhd_plass.fa

again?

> full disclosure, I entered `python -c import screed`, quote-less, on accident first so I hope that didnt mess it up?

it should have failed with a SyntaxError, right? No, didn't mess anything up :)
---
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by taylorreiter** [comment]
@hehouts is this the same environment we installed screed into on Tuesday to get this to work? I think you ran `conda install screed`

**Comment by hehouts** [comment]
Yes, I did run `conda install screed` and then remove-stop-plass.py ran fine. 

For clarity: the issue I was flagging was that the tutorial did not include `conda install screed` command, and it probably should? Apparently it had previously not been an issue for other people,  @taylorreiter suggested it was previously being installed as a dependency of sourmash. But when I ran the script very recently, screed had not already been installed, even though I has installed sourmash.

Does that clear things up, @ctb?

**Comment by hehouts** [comment]
Now realizing that if my original issue comment was just "add command `conda install screed` " this probably would have been a lot more clear

**Comment by ctb** [comment]
On Mon, May 11, 2020 at 03:39:45PM -0700, hehouts wrote:
> Yes, I did run `conda install screed` and then remove-stop-plass.py ran fine. 
> 
> For clarity: the issue I was flagging was that the tutorial did not include `conda install screed` command, and it probably should? Apparently it had previously not been an issue for other people,  @taylorreiter suggested it was previously being installed as a dependency of sourmash. But when I ran the script very recently, screed had not already been installed, even though I has installed sourmash.
> 
> Does that clear things up, @ctb?

Well, only that perhaps you already fixed the problem before I asked you
to test for it :).

screed is still a requirement for sourmash.

If you create a new environment with just sourmash installed, and run

% python -c 'import screed'

does it complain? I just ran

% conda activate sourmash-test8

and screed was installed OK.

**Comment by hehouts** [comment]
> If you create a new environment with just sourmash installed, and run `% python -c 'import screed'` does it complain?
...no. it returns prompt. 

I also installed plass into the test directory and ran it again. still working.

So... Im not able to recreate the issue... so I guess its not an issue..?

**Comment by ctb** [comment]
On Mon, May 11, 2020 at 04:15:58PM -0700, hehouts wrote:
> > If you create a new environment with just sourmash installed, and run `% python -c 'import screed'` does it complain?
> ...no. it returns prompt. 

ok, that means screed is installed!

> I also installed plass into the test directory and ran it again. still working.
> 
> So... Im not able to recreate the issue... so I guess its not an issue..?

it's ok, these kinds of heisenbugs happen :)

**Comment by ctb** [comment]
and now you have some ideas for debugging it if it comes up again!
