### ISSUE TITLE
conda environment name typo

### ISSUE THREAD

**Issue by clmattson** [dib-lab/dib_rotation#25]
This might be splitting hairs, but in file 02_conda, we create a rotation environment called "dib_rotation" but later in 05_starting_with_data, try to activate an environment called "2020_rotation" which I believe doesn't work because we haven't created it. Simple, but may confuse an inexperienced user.

**Comment by taylorreiter** [comment]
This is not splitting hairs and is very important, great catch! Would you like to try and put in a pull request that fixes this?

**Comment by clmattson** [comment]
Taylor,

Hmmmm sure! How do I do that? 🙂 I have used github before, but only for my own projects, if that makes sense? So I don't think I've ever made a pull request.

Courtney

--
Courtney Mattson
Ph.D. Student
Microbiology Graduate Group
University of California, Davis
(410)-610-9282
________________________________

**Comment by taylorreiter** [comment]
closed by #30
