### ISSUE TITLE
Add conda install kofamscan

### ISSUE THREAD

**Issue by bryshalm** [dib-lab/dib_rotation#33]
#### Annotating amino acid sequences

after 
> conda create -n kofamscan hmmer parallel ruby
conda activate kofamscan

then installing kofamscan needs to be **added** (_as explained by Tessa_)
>conda install kofamscan

Then checked with . . . . _though not necessarily_ 
>exec_annotation -h

 also if you could explain that kofamscan looks for a config file without have to call for it in the **exec_annotation** command would be helpful for newbies like me

**Comment by bluegenes** [comment]
I think after this, we figured out that we _do_ actually need to explicitly pass in the config file.

So the commands should now read:

```
exec_annotation -f mapper --config config.yaml -o query_nbhd_plass.clean_kofamscan.txt query_nbhd_plass.cdhit.fa 
```
and
```
exec_annotation -f mapper --config config.yaml -o GCA_001508995.1_ASM150899v1_protein_kofamscan.txt GCA_001508995.1_ASM150899v1_protein.faa 
```
