### ISSUE TITLE
add instructions for updating this site

### ISSUE THREAD

**Issue by bluegenes** [dib-lab/dib_rotation#39]
(Add a page with instructions for folks who want to update this site)

cc @hehouts 

draft content:

to edit the lessons (`*md` documents within the `doc` folder)
- `git clone `the repo
- make yourself a branch to work on `git checkout -b my-awesome-branch`
- make some changes in the markdown on your branch (git commit to save)
- if you added a new markdown document (needs to be in the `doc` folder):
  - update the `mkdocs.yml` `nav` section with the name and title for your new document

to view the updated rendered website locally:
- make a conda env, e.g. -  `mamba env create -n mkdocs mkdocs`
- activate that environment: `conda activate mkdocs`
- from the main repo (wherever mkdocs.yml is sitting), build the docs into a website: `mkdocs build`
- serves the site to a local webserver: `mkdocs serve` 
- a browser window should open automatically, but the address should also be visible on the terminal output, in case you need to input it manually.

When you're satisfied with your changes, open a pull request to integrate these changes into the main branch. When integrated, your changes will automatically render on the training website.

**Comment by taylorreiter** [comment]
closed by #40
