### ISSUE TITLE
Issues on the "Starting a Work Session" Page

### ISSUE THREAD

**Issue by nkavaler1** [dib-lab/dib_rotation#54]
it is actually 5 hours not 3 thats given in the code

>-t denotes that we want the computer for that amount of time (in this case, 3 hours).

Broken link:

>To transfer a file from a remote server to our own machines, we will use scp. To learn more about scp, see the bottom of [this tutorial](https://datacarpentry.org/shell-genomics/05-writing-scripts/).

**Comment by ccbaumler** [comment]
Closed by PR #68
