### ISSUE TITLE
kmer trim command notation

### ISSUE THREAD

**Issue by CorySchlesener** [dib-lab/dib_rotation#7]
I ran into an error trying to run the last command for k-mer trimming.
should the ${i} for files be manually replaced with file names? or if automated should the output direction  -o $i.abundtrim.fq.gz have brackets ${i} ?

**Comment by ctb** [comment]
hi Cory, what's the error you get?

**Comment by CorySchlesener** [comment]
Sorry I did not catch what the error was. I ran the command with written out designated file names in a tmux session, so the the error output is lost to the lines of output from the running program.

**Comment by taylorreiter** [comment]
Whoops! Thanks @CorySchlesener! I forgot to replace the for loop variables `${i}` and {$i} with the file input and output names :) updated!
