### ISSUE TITLE
Add database download step to Sourmash page

### ISSUE THREAD

**Issue by CorySchlesener** [dib-lab/dib_rotation#8]
The Sourmash run uses genbank-k31.lca.json database (not previously noted to download).
I found the download instruction in the Angus tutorial (linked on the page): https://angus.readthedocs.io/en/2019/sourmash.html

**Comment by taylorreiter** [comment]
Fixed! Thanks
https://github.com/dib-lab/dib_rotation/commit/f939f3af9bd8531cd934772a9313e130ef9241f6
